spring.application.name: core-api
spring.profiles.active: local

spring:
  config:
    import:
      - db-core.yml
      - core-redis.yml
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 200
    threads:
      max: 100
      min-spare: 10

---
spring.config.activate.on-profile: local
server:
  port: 8400

---
spring.config.activate.on-profile: dev
server:
  port: 8500
