version: '3.8'

services:
  mysql-meta:
    image: mysql:8.0
    container_name: e-commerces
    ports:
      - "3313:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: e-commerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ~/docker-volumes/e-commerce:/var/lib/mysql